<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search query_p</name>
   <tag></tag>
   <elementGuidId>a2295404-04d8-4f4d-886b-4491e3483250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ybar-sbq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ybar-sbq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4eeedb9-5686-4536-8b02-22435b742369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5b9e9ae-4c9e-4d4b-a5f4-09c1f379958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_8icko</value>
      <webElementGuid>5cb73b98-2f1d-4590-9d7a-433733ac7c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ybar-sbq</value>
      <webElementGuid>ec5be865-ed15-4e23-8cc9-105baa73928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4b96fd66-3084-4e25-9ad9-a80fe8454d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c09ea7ad-140b-443b-a4cd-cd755e1bb0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5ee90a0c-4cc0-46bc-9028-8bf1d205b2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da32a35f-87b2-4e12-bbcc-66557a9475ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>fff99e79-8ea8-4217-8e62-251e3ea03638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>c2c1221f-26e5-478e-bc52-1f86f7919509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3f4724f-cb59-4f86-b352-262baf13148b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-sbq&quot;)</value>
      <webElementGuid>d8d95b9c-5b75-48a6-8e21-f3374404f773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ybar-sbq']</value>
      <webElementGuid>9b6e0c71-1384-4775-a37a-e29a8fcee552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ybar-sf']/input</value>
      <webElementGuid>2c315858-7efd-461e-9c75-e7218ec365db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4361f66d-4bde-4b51-a0d1-823ec0a3403d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ybar-sbq' and @name = 'p']</value>
      <webElementGuid>a4e11c61-e00c-4fe8-bc74-888a42f34a40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
