<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text18_text18</name>
   <tag></tag>
   <elementGuidId>8e65cc3a-5d52-415e-a230-7a00d8d487b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8694c749-0cb1-431c-993f-f912d5035281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b47d91dc-8716-4fe7-ba43-744855d9236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text18</value>
      <webElementGuid>bdf2f8fe-a398-40b6-994a-991b04cb73c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text18&quot;)</value>
      <webElementGuid>c765168e-730a-479f-8c5f-12d7457d15a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text18']</value>
      <webElementGuid>cccd13fc-2d6e-4cf9-a8fd-355695f0470a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[18]</value>
      <webElementGuid>d3409308-1a75-4e54-bf64-7e15a074868c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text18']</value>
      <webElementGuid>4b235cf4-012a-400f-9121-77804a596681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
