<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text6_text6</name>
   <tag></tag>
   <elementGuidId>7b96da97-e7fc-40d6-bfd4-40ab4d67f9c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c81446d-c537-448d-b3be-22ad038b8eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3cc611a-c9a0-4f41-bd71-f760655b53d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text6</value>
      <webElementGuid>edda6880-d47e-45b1-997f-055e65a7c056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text6&quot;)</value>
      <webElementGuid>69a26932-12a5-4e58-ad09-a9791cd0d66d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text6']</value>
      <webElementGuid>bf976315-ca53-48b6-96a7-c536085bc079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>95140345-e653-4516-8f20-1d2be68e9cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text6']</value>
      <webElementGuid>0e2e40cc-2263-43cd-902d-61dc571644c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
