<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text31_text31</name>
   <tag></tag>
   <elementGuidId>bd5a3d8b-38e2-4845-b5c9-fe3e8f253197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text31</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text31']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fe0af18-8d3e-4fde-8476-8f24652f9542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ec060b9-466b-4085-8de0-1826c9d4a014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text31</value>
      <webElementGuid>0ec6f06a-1e1f-4931-9cd2-3b58cfdc32da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text31&quot;)</value>
      <webElementGuid>eb80ccfc-35e8-496f-a745-c0488e403c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text31']</value>
      <webElementGuid>168f5ec9-aca2-42cc-a8ae-b499f5ffd8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[31]</value>
      <webElementGuid>48a4af9a-3317-47e4-b59b-a55198b0372e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text31']</value>
      <webElementGuid>3363ee9c-8be2-4095-a521-7c6406726b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
