<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text5_text5</name>
   <tag></tag>
   <elementGuidId>4bf5fcfb-b718-4e43-b618-89c40e355536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>783d01b7-0b6e-416d-a78c-9f792890d9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8855c7f1-6c7b-4f06-803d-dd849bc028a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text5</value>
      <webElementGuid>9c0ceeb5-853d-43cf-a261-2d7dc8821c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text5&quot;)</value>
      <webElementGuid>e05c5f4f-4e03-4af8-98e7-8db443f6e300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text5']</value>
      <webElementGuid>f3b498bc-3cfb-4e1e-a84c-ce1ade34fe8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>5d04a1bc-4dfc-48fb-a694-da23fc7fbb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text5']</value>
      <webElementGuid>f8bda47d-15bf-48bf-9e7b-9c6ce16cb4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
