<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text15_text15</name>
   <tag></tag>
   <elementGuidId>a67140a5-6bbd-46d3-ae21-e7a6f21132c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cf9b54e-7c57-4444-9d6a-5bf2e34f8d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>474c0289-649f-41bf-9f4f-14df4459aac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text15</value>
      <webElementGuid>47ad788d-de7d-4cf7-8497-52d583c45756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text15&quot;)</value>
      <webElementGuid>5c562591-35f6-4986-9db3-084742283aff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text15']</value>
      <webElementGuid>1a3e24d3-64d0-4c41-ba21-f52d856c7698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[15]</value>
      <webElementGuid>eb3774cd-317d-460c-a34d-c5fe84e48962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text15']</value>
      <webElementGuid>6bb08d8b-e048-4b84-9c62-a7d969132037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
