<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text39_text39</name>
   <tag></tag>
   <elementGuidId>71f37681-83e1-4ca5-90a7-f7cf103e302b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text39</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text39']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffbd01df-3dda-4cde-8d45-443987b9fe14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9129282f-bc9d-480a-92fe-2d1220722b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text39</value>
      <webElementGuid>dc4d766a-0e92-46ba-914b-545478c923fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text39&quot;)</value>
      <webElementGuid>750f9315-2d96-47af-b3f1-b9ab6fb6c757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text39']</value>
      <webElementGuid>7e5b3ef5-44c9-4996-88b9-3998c933ad4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[39]</value>
      <webElementGuid>1bbd0df4-62c8-4173-a796-c37c008de370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text39']</value>
      <webElementGuid>5c349984-ce49-4d71-8300-89ade1c37edd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
