<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text17_text17</name>
   <tag></tag>
   <elementGuidId>2df1aaae-efdf-4ccf-801e-d75578555749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5864d021-003a-4f0b-9995-309e84c1b24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37231eae-b780-4577-bd16-31b367a48891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text17</value>
      <webElementGuid>26756662-aed1-4e37-a546-37afde53da4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text17&quot;)</value>
      <webElementGuid>d32d9379-c4ff-4914-8115-ae7ca51da78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text17']</value>
      <webElementGuid>2ab581b4-0dbc-43c6-ae47-31557edd070c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[17]</value>
      <webElementGuid>01253fcd-e1f6-48ca-a916-2dd257430a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text17']</value>
      <webElementGuid>50156e1f-1233-4870-a9b7-3a6b6a6a4b9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
