<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text27_text27</name>
   <tag></tag>
   <elementGuidId>04e0abcd-0228-4e7e-a00f-23c76b1cc388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4785da3-f8ac-4d4a-9dc3-9c98aadb66ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>060f628e-11c6-447e-b798-1b75775b5e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text27</value>
      <webElementGuid>6337a028-6a56-414b-b8a8-c8942d7d800b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text27&quot;)</value>
      <webElementGuid>4a2cac74-d4c1-4c60-98eb-74ffd1786dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text27']</value>
      <webElementGuid>caeefd5f-1f84-421c-a428-574601567d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>bad0c264-93cc-4562-8344-b753cfc41d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text27']</value>
      <webElementGuid>83698aa2-8c11-40d9-91c9-707d6a03f58c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
