<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text19_text19</name>
   <tag></tag>
   <elementGuidId>0cee8d09-6065-4b1c-9af7-1b3816cb9a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55b768f7-9d38-4b4e-abff-27c162c5f4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79db05d0-3d72-4988-a49e-fc6043608410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text19</value>
      <webElementGuid>b5626f8d-73ed-4238-9050-a034662be640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text19&quot;)</value>
      <webElementGuid>4a4cb237-ca67-4b69-a4df-4bbd5d75704b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text19']</value>
      <webElementGuid>52bfc525-255b-4502-afb7-d62796e8a487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[19]</value>
      <webElementGuid>279aec48-5253-4341-815c-e7ec47b47397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text19']</value>
      <webElementGuid>1cf81ea0-e4e5-40fe-9631-8dac040e6408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
