<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text8_text8</name>
   <tag></tag>
   <elementGuidId>c281fea4-7ef4-471f-a9e7-b9c93e347bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>040c43c7-cc27-4e9f-a3ef-ae2e889f47ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d67ba94b-0e0d-42ec-b9e0-bc8d2da91a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text8</value>
      <webElementGuid>6eb84cee-a49f-461f-a2e5-5f5c44b63009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text8&quot;)</value>
      <webElementGuid>78a5ab57-0fc1-42a4-90a9-b3f01c8b2313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text8']</value>
      <webElementGuid>c8ed562b-fec9-481b-a95d-fa0c0d5d5bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>875502b1-6959-480e-b637-5f96ce8afede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text8']</value>
      <webElementGuid>0a82bade-6666-40ac-a3e7-c983cba01f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
