<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text9_text9</name>
   <tag></tag>
   <elementGuidId>d48ec799-2f04-4ca8-9f39-5e323cbfb103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1da1c617-aab1-49f3-a7b4-47a32812df55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16aebaf2-c958-4c30-8897-cbb550bbd3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text9</value>
      <webElementGuid>64d196e6-4861-45d0-b1e5-8d4a2bae387a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text9&quot;)</value>
      <webElementGuid>aa165672-18aa-4523-9bec-d4f2a16ca886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text9']</value>
      <webElementGuid>5056547f-18ca-4fcc-9b09-495f1e29be94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>de25d7c3-a800-41e7-8d56-b33c8412a739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text9']</value>
      <webElementGuid>c3af4d42-c953-456c-a071-840fa6aec676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
