<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio6_radio7</name>
   <tag></tag>
   <elementGuidId>470f5465-da65-4154-bd4e-89620c44cde0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9bb8c9e-3076-4d75-b30b-17827b398359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bfa7fe00-ddc9-4d81-86ce-3e67796f454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio7</value>
      <webElementGuid>64fd7036-c495-4051-831b-400bae17cb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio7</value>
      <webElementGuid>d0114644-0083-4dcf-902a-dfe19357c32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio7&quot;)</value>
      <webElementGuid>d21a4329-07fb-4e6a-a0fe-e5431f627462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio7']</value>
      <webElementGuid>061ae172-8dfb-4cd6-921e-97df15b8a45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>b9e1fbe9-e62f-417e-969b-a72ee03c83e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio7']</value>
      <webElementGuid>dbacac4b-ac6c-4051-9342-db4f8c9e51ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
