<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text4_text4</name>
   <tag></tag>
   <elementGuidId>9245defa-75c3-4ec3-a5b6-5ab14c4f4c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f4057a7-eba3-4738-bb53-8f680d2dd56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76cfcfa0-ba23-4b42-887b-a4bec4b53973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text4</value>
      <webElementGuid>6c8e8011-60dc-469c-8742-47825bbc2193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text4&quot;)</value>
      <webElementGuid>9a20864d-9916-46ef-b2dd-56f659e68b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text4']</value>
      <webElementGuid>014abba0-3b4a-40a7-b061-17b4fd4e92dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>20e98e2f-44b9-429b-8264-336adb8ddc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text4']</value>
      <webElementGuid>0c0f4a94-6aa9-43be-983d-dec67e6ee5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
