<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio3_radio4</name>
   <tag></tag>
   <elementGuidId>15b09401-9bbe-4d2d-9003-405ecedb972c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc49f3c1-ef19-4d7a-ae6a-c3c0c75fcf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7b1c4f33-6d94-4296-a118-6a8782eef591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio4</value>
      <webElementGuid>5be3602f-09b6-41e0-ba6f-51f579a92d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio4</value>
      <webElementGuid>d739cf00-5736-4075-ad0b-7b7c2bd18449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio4&quot;)</value>
      <webElementGuid>e91cd2ce-94de-44c8-a53f-aebc056d24b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio4']</value>
      <webElementGuid>73c2f349-5297-4407-a3f4-9b5a739252e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[24]</value>
      <webElementGuid>40d7a7ac-5344-400c-a74c-ad01113eaeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio4']</value>
      <webElementGuid>89a689b0-117f-46b8-916c-6606e61b53f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
