<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text1_text1</name>
   <tag></tag>
   <elementGuidId>7aeb2697-8d63-42e3-984b-5b2b27ed65b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4b373f8-553f-44f8-8bd9-848fc77aebcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0cae167-814d-47c0-ad5a-d76d0630ee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text1</value>
      <webElementGuid>ced169be-b7c9-40c8-93eb-bbf3310d63ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text1&quot;)</value>
      <webElementGuid>533fd6f4-58ef-4ce1-b541-1503514d1ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text1']</value>
      <webElementGuid>7bd3d0bb-1356-489e-91e2-6693045cceef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>db5d2dae-ac88-4bc8-a353-2ce30e5f6740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text1']</value>
      <webElementGuid>4b24862c-0337-4be9-9333-a86039c3719d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
