<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text7_text7</name>
   <tag></tag>
   <elementGuidId>2eb026c7-f3f2-48c7-985d-05220e9bd00d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a257953f-60b2-4022-98e5-ade83825bd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>353a1a59-628a-490d-b130-99ffe5eb15a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text7</value>
      <webElementGuid>e263e9cd-e30e-4f7f-a963-5d3ff015f475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text7&quot;)</value>
      <webElementGuid>56150c3e-2e0c-410e-8152-51225207177c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text7']</value>
      <webElementGuid>3fb92f65-ae0c-40fc-960e-eed812b16f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>7d6e35b2-3fd6-433b-b6e0-45d1c1b84f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text7']</value>
      <webElementGuid>8ffcb6e9-d5a8-4c9f-8ff6-6c7e9821d304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
