<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text2_text2</name>
   <tag></tag>
   <elementGuidId>a3f62df3-2eea-4fd6-a523-921fbb30b603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cde1116f-72b0-4fac-98b8-ffb24c33c4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdca7810-9338-4b16-bbb8-fdd2572e8089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text2</value>
      <webElementGuid>d27e0928-d39f-41d9-8d4c-45f1247adab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text2&quot;)</value>
      <webElementGuid>382d430e-deb7-4941-8d7b-01930782bc0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text2']</value>
      <webElementGuid>91baee30-a4dc-4a7e-9650-911785043d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>64add603-d200-4247-8ca0-0be213d3fae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text2']</value>
      <webElementGuid>5d4667aa-5a5c-447d-a88d-0c897abaef64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
