<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value1          value2          valu_9f7bd8_1</name>
   <tag></tag>
   <elementGuidId>f4199d5a-1c29-42d4-80f8-245327268048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>75bd9428-a803-45fe-8098-2bb1844348b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option3</value>
      <webElementGuid>6ad115a9-f248-4d34-a79b-ab19ca3f3979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          value1
          value2
          value3
          value4
        </value>
      <webElementGuid>5ba4a79d-1e71-4a23-b28a-cfb390bfadf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option3&quot;)</value>
      <webElementGuid>155c2995-ff7d-4442-af05-c9e1098189c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option3']</value>
      <webElementGuid>c0147270-f833-4fb7-a600-bb5102bfb9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option3:'])[1]/following::select[1]</value>
      <webElementGuid>495cad6e-5756-4640-b537-40724bb90a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option2:'])[1]/following::select[2]</value>
      <webElementGuid>8b1c8440-4c4a-42a2-bbd9-c1ac93b436a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option4:'])[1]/preceding::select[1]</value>
      <webElementGuid>deba684a-f646-4289-b19a-e9fe40aff47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option5:'])[1]/preceding::select[2]</value>
      <webElementGuid>20be2926-d580-48e0-8b28-c8f6657f0c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>c9572d36-3c55-4776-a684-d624de4cf501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option3' and (text() = '
          value1
          value2
          value3
          value4
        ' or . = '
          value1
          value2
          value3
          value4
        ')]</value>
      <webElementGuid>bd7cf3c0-5084-4fc5-b0c5-5d0de2ceb1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
